// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcNFv9bqVgd8U_eAz-7usMeONgGABH9sM',
    appId: '1:446715870806:web:6993750ed069c0b26905f7',
    messagingSenderId: '446715870806',
    projectId: 'testfirebase-1-91f1c',
    authDomain: 'testfirebase-1-91f1c.firebaseapp.com',
    storageBucket: 'testfirebase-1-91f1c.appspot.com',
    measurementId: 'G-MWQW2Y880F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWuxNR2Wg-_5TEO0w9LijVI4Kc94Hx86w',
    appId: '1:446715870806:android:d9fcfeb8baaf5f646905f7',
    messagingSenderId: '446715870806',
    projectId: 'testfirebase-1-91f1c',
    storageBucket: 'testfirebase-1-91f1c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC07-1mMPefAtbFBdeS-iZ7m3bNBwWesKQ',
    appId: '1:446715870806:ios:f5e7a315acbc47b26905f7',
    messagingSenderId: '446715870806',
    projectId: 'testfirebase-1-91f1c',
    storageBucket: 'testfirebase-1-91f1c.appspot.com',
    iosBundleId: 'com.example.testfirebase1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC07-1mMPefAtbFBdeS-iZ7m3bNBwWesKQ',
    appId: '1:446715870806:ios:f5e7a315acbc47b26905f7',
    messagingSenderId: '446715870806',
    projectId: 'testfirebase-1-91f1c',
    storageBucket: 'testfirebase-1-91f1c.appspot.com',
    iosBundleId: 'com.example.testfirebase1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcNFv9bqVgd8U_eAz-7usMeONgGABH9sM',
    appId: '1:446715870806:web:7031c81cc17c34a46905f7',
    messagingSenderId: '446715870806',
    projectId: 'testfirebase-1-91f1c',
    authDomain: 'testfirebase-1-91f1c.firebaseapp.com',
    storageBucket: 'testfirebase-1-91f1c.appspot.com',
    measurementId: 'G-8HP08CLPNZ',
  );
}
